=== kodePhile/jacklyn-codebase/jacklyn-shared/src/main/resources/dtd/jacklyn-module-config_2_0.dtd
<?xml encoding="UTF-8"?>
<!--
  Copyright 2018-2019 The Code Department.
  
  Licensed under the Apache License, Version 2.0 (the "License"); you may not
  use this file except in compliance with the License. You may obtain a copy of
  the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations under
  the License.
-->

<!--
This is the XML DTD for the Jacklyn module configuration XML file.
Configuration files should include a DOCTYPE of the following form:

  <!DOCTYPE unify PUBLIC
	"-//The Code Department//DTD Jacklyn Module 2.0//EN"
	"https://tcdng.com/dtd/jacklyn-module-config_2_0.dtd">
-->


<!ELEMENT module (audits?,archives?,shortcut-tiles?,menus?,input-controls?,notification-templates?,privileges?,reports?,sys-parameters?)>
<!ATTLIST module description CDATA #REQUIRED>
<!ATTLIST module name NMTOKEN #REQUIRED>

<!ELEMENT audits (audit+)>

<!ELEMENT archives (archive+)>

<!ELEMENT shortcut-tiles (shortcut-tile+)>

<!ELEMENT menus (menu+)>

<!ELEMENT input-controls (input-control+)>

<!ELEMENT privileges (privilege-group+)>

<!ELEMENT reports (report-group+)>

<!ELEMENT notification-templates (notification-template+)>

<!ELEMENT sys-parameters (sys-parameter+)>

<!ELEMENT audit EMPTY>
<!ATTLIST audit action (search|create|view|update|delete|login|logout|generate|upload|download|workflow|miscellaneous|system) #REQUIRED>
<!ATTLIST audit description CDATA #REQUIRED>
<!ATTLIST audit name NMTOKEN #REQUIRED>

<!ELEMENT archive EMPTY>
<!ATTLIST archive archivable CDATA #REQUIRED>
<!ATTLIST archive description CDATA #REQUIRED>
<!ATTLIST archive name NMTOKEN #REQUIRED>

<!ELEMENT shortcut-tile EMPTY>
<!ATTLIST shortcut-tile caption CDATA #REQUIRED>
<!ATTLIST shortcut-tile description CDATA #REQUIRED>
<!ATTLIST shortcut-tile image CDATA #IMPLIED>
<!ATTLIST shortcut-tile generator CDATA #IMPLIED>
<!ATTLIST shortcut-tile name NMTOKEN #REQUIRED>
<!ATTLIST shortcut-tile path CDATA #REQUIRED>
<!ATTLIST shortcut-tile landscape (true|false) "false">

<!ELEMENT menu (menuitem+)>
<!ATTLIST menu caption CDATA #REQUIRED>
<!ATTLIST menu description CDATA #REQUIRED>
<!ATTLIST menu name NMTOKEN #REQUIRED>
<!ATTLIST menu pageCaption CDATA #IMPLIED>
<!ATTLIST menu path CDATA #IMPLIED>
<!ATTLIST menu remotePath CDATA #IMPLIED>

<!ELEMENT input-control EMPTY>
<!ATTLIST input-control description CDATA #REQUIRED>
<!ATTLIST input-control editor CDATA #REQUIRED>
<!ATTLIST input-control name NMTOKEN #REQUIRED>

<!ELEMENT privilege-group (privilege+)>
<!ATTLIST privilege-group category NMTOKEN #IMPLIED>

<!ELEMENT report-group (report+)>
<!ATTLIST report-group description CDATA #REQUIRED>
<!ATTLIST report-group name NMTOKEN #REQUIRED>

<!ELEMENT notification-template EMPTY>
<!ATTLIST notification-template subject CDATA #REQUIRED>
<!ATTLIST notification-template template CDATA #REQUIRED>
<!ATTLIST notification-template actionLink CDATA #IMPLIED>
<!ATTLIST notification-template messageType (information|warning|action) "information">
<!ATTLIST notification-template html (true|false) "false">
<!ATTLIST notification-template name NMTOKEN #REQUIRED>
<!ATTLIST notification-template description CDATA #REQUIRED>

<!ELEMENT sys-parameter EMPTY>
<!ATTLIST sys-parameter control (true|false) "false">
<!ATTLIST sys-parameter defaultVal CDATA #IMPLIED>
<!ATTLIST sys-parameter description CDATA #REQUIRED>
<!ATTLIST sys-parameter editable (true|false) "true">
<!ATTLIST sys-parameter editor CDATA #REQUIRED>
<!ATTLIST sys-parameter name NMTOKEN #REQUIRED>
<!ATTLIST sys-parameter type (boolean|number|string) "string">

<!ELEMENT menuitem EMPTY>
<!ATTLIST menuitem caption CDATA #REQUIRED>
<!ATTLIST menuitem description CDATA #REQUIRED>
<!ATTLIST menuitem name NMTOKEN #REQUIRED>
<!ATTLIST menuitem pageCaption CDATA #REQUIRED>
<!ATTLIST menuitem path CDATA #REQUIRED>
<!ATTLIST menuitem remotePath CDATA #IMPLIED>

<!ELEMENT privilege EMPTY>
<!ATTLIST privilege description CDATA #REQUIRED>
<!ATTLIST privilege name NMTOKEN #REQUIRED>

<!ELEMENT report (columns?,parameters?,filter?)>
<!ATTLIST report description CDATA #REQUIRED>
<!ATTLIST report name NMTOKEN #REQUIRED>
<!ATTLIST report title CDATA #REQUIRED>
<!ATTLIST report reportable NMTOKEN #IMPLIED>
<!ATTLIST report template CDATA #IMPLIED>
<!ATTLIST report processor NMTOKEN #IMPLIED>
<!ATTLIST report layout NMTOKEN #IMPLIED>
<!ATTLIST report invertGroupColors (true|false) "false">
<!ATTLIST report landscape (true|false) "false">
<!ATTLIST report underlineRows (true|false) "false">
<!ATTLIST report shadeOddRows (true|false) "false">

<!ELEMENT columns (column+)>

<!ELEMENT parameters (parameter+)>

<!ELEMENT column EMPTY>
<!ATTLIST column description CDATA #REQUIRED>
<!ATTLIST column field NMTOKEN #REQUIRED>
<!ATTLIST column type CDATA #IMPLIED>
<!ATTLIST column formatter CDATA #IMPLIED>
<!ATTLIST column width CDATA #IMPLIED>
<!ATTLIST column order (ascending|descending) #IMPLIED>
<!ATTLIST column halign (left|center|right|justified) #IMPLIED>
<!ATTLIST column group (true|false) "false">
<!ATTLIST column groupOnNewPage (true|false) "false">
<!ATTLIST column sum (true|false) "false">

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter description CDATA #REQUIRED>
<!ATTLIST parameter editor CDATA #REQUIRED>
<!ATTLIST parameter label CDATA #REQUIRED>
<!ATTLIST parameter mandatory (true|false) "false">
<!ATTLIST parameter defaultVal CDATA #IMPLIED>
<!ATTLIST parameter name NMTOKEN #REQUIRED>
<!ATTLIST parameter type (char|boolean|short|integer|long|float|double|decimal|date|string|blob) "string">

<!ELEMENT filter (filter*)>
<!ATTLIST filter field NMTOKEN #IMPLIED>
<!ATTLIST filter op (equals|not_equal|less_than|less_or_equal|greater|greater_or_equal|between|not_between|amongst|not_amongst|like|not_like|begins_with|not_begin_with|ends_with|not_end_with|is_null|is_not_null|and|or) #REQUIRED>
<!ATTLIST filter useParameter (true|false) "false">
<!ATTLIST filter value1 CDATA #IMPLIED>
<!ATTLIST filter value2 CDATA #IMPLIED>

=== kodePhile/jacklyn-codebase/jacklyn-workflow/src/main/resources/config/workflow-module.xml
<?xml version="1.0"?>
<!DOCTYPE unify PUBLIC
  "-//The Code Department//DTD Jacklyn Module 2.0//EN"
  "https://tcdng.com/dtd/jacklyn-module-config_2_0.dtd">
<!--
  Copyright 2018-2020 The Code Department.
  
  Licensed under the Apache License, Version 2.0 (the "License"); you may not
  use this file except in compliance with the License. You may obtain a copy of
  the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  License for the specific language governing permissions and limitations under
  the License.
-->

<!-- Jacklyn configuration for workflow module -->
<module name="workflow" description="$m{workflow.module}">
	<menus>
		<menu name="wf-mainworkflow" caption="$m{workflow.menu.title}"
			description="$m{workflow.menu.main}">
			<menuitem name="wf-wfcategory-manage" caption="$m{workflow.wfcategory.menu.title}"
				pageCaption="$m{workflow.wfcategory.manage}"
				description="$m{workflow.wfcategory.menuitem}" path="/workflow/wfcategory/openPage" />
			<menuitem name="wf-publish-manage" caption="$m{workflow.wfcategory.publish.menu.title}"
				pageCaption="$m{workflow.wfcategory.publish.manage}" description="$m{workflow.wfcategory.publish.menuitem}"
				path="/workflow/wfpublishcategory/openPage" />
			<menuitem name="wf-manual-item" caption="$m{workflow.wfcategory.manualinit.menu.title}"
				pageCaption="$m{workflow.wfcategory.manualinit.manage}" description="$m{workflow.wfcategory.manualinit.menuitem}"
				path="/workflow/manualworkiteminitiation/openPage" />
			<menuitem name="wf-wfdoc-manage" caption="$m{workflow.wfdoc.menu.title}"
				pageCaption="$m{workflow.wfdoc.manage}"
				description="$m{workflow.wfdoc.menuitem}" path="/workflow/wfdoc/openPage" />
			<menuitem name="wf-wftemplate-manage" caption="$m{workflow.wftemplate.menu.title}"
				pageCaption="$m{workflow.wftemplate.manage}"
				description="$m{workflow.wftemplate.menuitem}" path="/workflow/wftemplate/openPage" />
			<menuitem name="wf-userwfitems-manage" caption="$m{workflow.userworkflowitems.menu.title}"
				pageCaption="$m{workflow.userworkflowitems.manage}"
				description="$m{workflow.userworkflowitems.menuitem}" path="/workflow/userworkflowitems/openPage"/>
		</menu>
	</menus>
	<privileges>
		<privilege-group>
			<privilege name="wf-wfcategory-add" description="$m{workflow.privilege.wfcategory.add}" />
			<privilege name="wf-wfcategory-edit" description="$m{workflow.privilege.wfcategory.edit}" />
			<privilege name="wf-wfcategory-view" description="$m{workflow.privilege.wfcategory.view}" />
			<privilege name="wf-wfcategory-delete" description="$m{workflow.privilege.wfcategory.delete}" />
			<privilege name="wf-wfdoc-add" description="$m{workflow.privilege.wfdoc.add}" />
			<privilege name="wf-wfdoc-edit" description="$m{workflow.privilege.wfdoc.edit}" />
			<privilege name="wf-wfdoc-view" description="$m{workflow.privilege.wfdoc.view}" />
			<privilege name="wf-wfdoc-delete" description="$m{workflow.privilege.wfdoc.delete}" />
			<privilege name="wf-wftemplate-add" description="$m{workflow.privilege.wftemplate.add}" />
			<privilege name="wf-wftemplate-view" description="$m{workflow.privilege.wftemplate.view}" />
			<privilege name="wf-wftemplate-edit" description="$m{workflow.privilege.wftemplate.edit}" />
			<privilege name="wf-wftemplate-delete"
				description="$m{workflow.privilege.wftemplate.delete}" />
		</privilege-group>
	</privileges>
    <sys-parameters>
        <sys-parameter name="WFL-0001" defaultVal=""
            description="$m{workflow.sysparam.emailnotificationchannel}" editor="!ui-select list:emailnotificationchannellist listKey:name"
            type="string" />
        <sys-parameter name="WFL-0002" defaultVal=""
            description="$m{workflow.sysparam.smsnotificationchannel}" editor="!ui-select list:smsnotificationchannellist listKey:name"
            type="string" />
        <sys-parameter name="WFL-0003" defaultVal="defWfSysNotifChannel"
            description="$m{workflow.sysparam.systemnotificationchannel}" editor="!ui-select list:systemnotificationchannellist listKey:name"
            type="string" />
        <sys-parameter name="WFL-0004"
            defaultVal="myWorkItemsDashboard" description="$m{workflow.sysparam.myworkitemsdashboard}"
            editor="!ui-text size:48"/>
        <sys-parameter name="WFL-0005"
            defaultVal="myWorkItemsGraphDashboard" description="$m{workflow.sysparam.myworkitemsgraphdashboard}"
            editor="!ui-text size:48"/>
    </sys-parameters>
</module>

=== kodePhile/jacklyn-codebase/jacklyn-archiving/src/main/resources/config/archiving-module.xml
<?xml version="1.0"?>
<!DOCTYPE unify PUBLIC
  "-//The Code Department//DTD Jacklyn Module 2.0//EN"
  "https://tcdng.com/dtd/jacklyn-module-config_2_0.dtd">
<module name="archiving" description="$m{archiving.module}">
	<menus>
		<menu name="arc-mainarchiving" description="$m{archiving.menu.main}"
			caption="$m{archiving.menu.title}">
			<menuitem name="arc-managearchivabledefinition" description="$m{archiving.menuitem.archivabledefinition}"
				caption="$m{archiving.archivabledefinition.menu.title}" pageCaption="$m{archiving.archivabledefinition.manage}"
				path="/archiving/archivabledefinition/openPage" />
			<menuitem name="arc-managefilearchiveconfig" description="$m{archiving.menuitem.filearchiveconfig}"
				caption="$m{archiving.filearchiveconfig.menu.title}" pageCaption="$m{archiving.filearchiveconfig.manage}"
				path="/archiving/filearchiveconfig/openPage" />
		</menu>
	</menus>
	<privileges>
		<privilege-group>
			<privilege name="arc-archivabledefinitionview"
				description="$m{archiving.privilege.archivabledefinition.view}" />
			<privilege name="arc-filearchiveconfigadd"
				description="$m{archiving.privilege.filearchiveconfig.add}" />
			<privilege name="arc-filearchiveconfigedit"
				description="$m{archiving.privilege.filearchiveconfig.edit}" />
			<privilege name="arc-filearchiveconfigview"
				description="$m{archiving.privilege.filearchiveconfig.view}" />
			<privilege name="arc-filearchiveconfigdelete"
				description="$m{archiving.privilege.filearchiveconfig.delete}" />
		</privilege-group>
	</privileges>
</module>
